Repository rak517/Epigram, pull requests merged in 2025-03, with the labels that each got.

#5 EP-10 README.md 초안 작성
  README.md
Labels: Priority: Low 🐢, Type: Docs 📃

#20 EP-15 공용 인풋 컴포넌트 구현
  src/components/.gitkeep
  src/components/ui/Field/Base.tsx
  src/components/ui/Field/Input.tsx
  src/components/ui/Field/index.tsx
  src/components/ui/Field/types.ts
  src/stories/.gitkeep
  src/stories/Field/Input/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#27 EP-25 StoryBook 정적 사이트 배포 자동화 세팅
  .github/workflows/storybook.yml
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/app/globals.css
  src/components/.gitkeep
  src/components/ui/Field/Base.tsx
  src/components/ui/Field/Input.tsx
  src/components/ui/Field/index.tsx
  src/components/ui/Field/types.ts
  src/components/ui/buttons/index.tsx
  src/stories/.gitkeep
  src/stories/Field/Input/index.stories.tsx
  src/stories/buttons/index.stories.tsx
  src/utils/cn.ts
Labels: Priority: Low 🐢, Type: Deploy 🌏, Type: Setting ⚙

#21 EP-18 공용 Avatar 컴포넌트 구현
  next.config.ts
  src/components/ui/avatars/index.tsx
  src/components/ui/buttons/index.tsx
  src/stories/avatars/index.stories.tsx
  src/stories/buttons/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#22 EP-17 공용 Chip 컴포넌트 구현
  src/components/ui/Chip/index.tsx
  src/stories/Chip/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#24 EP-19 공용 Floating Action Button 구현
  src/assets/icons/Upper_Arrow.svg
  src/components/ui/buttons/FloatingButton.tsx
  src/stories/buttons/FloatingButton.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#28 EP-14 공용 side-bar 컴포넌트 구현
  src/assets/icons/X.svg
  src/assets/icons/sideBar.svg
  src/components/ui/keywordCard/index.tsx
  src/components/ui/sideBar/index.tsx
  src/stories/sideBar/index.stories.tsx
Labels: Priority: Low 🐢, Type: Feature ✨

#32 EP-37 이미지, 아이콘 파일 추가
  src/assets/icons/.gitkeep
  src/assets/icons/arrow_left.svg
  src/assets/icons/arrow_right.svg
  src/assets/icons/camera.svg
  src/assets/icons/darhboard.svg
  src/assets/icons/down_black.svg
  src/assets/icons/down_gray.svg
  src/assets/icons/external-link.svg
  src/assets/icons/ic_up.svg
  src/assets/icons/kebob.svg
  src/assets/icons/like.svg
  src/assets/icons/plus.svg
  src/assets/icons/share.svg
  src/assets/icons/sort.svg
  src/assets/icons/x_black.svg
  src/assets/icons/x_gray.svg
  src/assets/images/.gitkeep
  src/assets/images/empty_epigram.svg
  src/assets/images/logo_google.svg
  src/assets/images/logo_kakao.svg
  src/assets/images/logo_naver.svg
  src/assets/images/warning.svg
  src/assets/landings/.gitkeep
  src/assets/landings/desktop-1.png
  src/assets/landings/desktop-2.png
  src/assets/landings/desktop-3.png
  src/assets/landings/desktop-4.png
  src/assets/landings/mobile-1.png
  src/assets/landings/mobile-2.png
  src/assets/landings/mobile-3.png
  src/assets/landings/mobile-4.png
  src/assets/landings/tablet-1.png
  src/assets/landings/tablet-2.png
  src/assets/landings/tablet-3.png
  src/assets/landings/tablet-4.png
Labels: Priority: Medium :bookmark:, Type: Setting ⚙

#34 EP-16 공용 text area 컴포넌트 구현
  src/components/ui/textarea/index.tsx
  src/stories/textarea/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#35 EP-21 공용 DropdownMenu 컴포넌트 기능 구현
  src/assets/icons/dropdown_icon.svg
  src/components/ui/DropdownMenu/index.tsx
  src/stories/DropdownMenu/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#42 EP-39 공용 radio button 컴포넌트 구현
  src/components/ui/radio/RadioGroup.tsx
  src/components/ui/radio/RadioGroupItem.tsx
  src/components/ui/radio/RadioItem.tsx
  src/components/ui/radio/RadioLabel.tsx
  src/stories/radio/radioGroup.stories.tsx
  src/stories/radio/radioItem.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#36 EP-23 공용 keyword-card 컴포넌트 기능 구현
  src/components/ui/keywordCard/index.tsx
  src/stories/keywordCard/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#41 EP-40 공용 toggle-btn 컴포넌트 기능 구현
  src/components/ui/toggleBtn/index.tsx
  src/stories/toggleBtn/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#45 EP-36 공용 emotion 컴포넌트 구현
  src/components/ui/emotion/index.tsx
  src/stories/emotion/index.stories.tsx
Labels: Priority: Low 🐢, Type: Feature ✨

#46 EP-38 회원가입 페이지 구현
  jest.setup.ts
  package-lock.json
  package.json
  src/apis/.gitkeep
  src/apis/QueryProvider.tsx
  src/apis/auth/index.ts
  src/apis/auth/queries.tsx
  src/apis/user/index.ts
  src/apis/user/queries.tsx
  src/app/(after-login)/addepigram/page.tsx
  src/app/(after-login)/epigrams/[id]/edit/page.tsx
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/page.tsx
  src/app/(after-login)/feed/page.tsx
  src/app/(after-login)/mypage/page.tsx
  src/app/(after-login)/search/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/oauth/signup/[...provider]/route.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/[...endpoint]/route.ts
  src/app/api/auth/refresh-token/route.ts
  src/app/layout.tsx
  src/assets/icons/closed_eye.svg
  src/assets/icons/opend_eye.svg
  src/assets/images/logo.png
  src/components/auth/SignupForm.tsx
  src/components/auth/SocialButtonGroup.tsx
  src/constants/.gitkeep
  src/constants/route.ts
  src/middleware.ts
  src/schemas/index.ts
  src/types/index.ts
  src/utils/network/axiosClientHelper.ts
  src/utils/network/axiosServerHelper.ts
  src/utils/network/convertGoogleToken.ts
  src/utils/network/errorResponse.ts
  src/utils/network/extractProviderAndCode.ts
  src/utils/network/getErrorMessage.ts
  src/utils/network/getExpirationDate.ts
  src/utils/network/safeResponse.ts
  tests/SignupForm.test.tsx
  tests/getErrorMessage.test.ts
  tests/getExpirationDate.test.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Setting ⚙, Type: Test 🧪

#52 NO-ISSUE playwright 셋업 수정
  .github/workflows/ci-main.yml
  playwright.config.ts
Labels: Priority: High 🔥, Type: Setting ⚙

#47 EP-41 공용 rounded-button 컴포넌트 구현
  src/components/ui/buttons/roundedButton.tsx
  src/stories/buttons/roundedButton.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#50 EP-47 공용 side-bar 컴포넌트 리팩토링 (비즈니스 로직 제거 및 재사용성)
  src/components/ui/sideBar/index.tsx
  src/stories/sideBar/index.stories.tsx
Labels: Priority: Low 🐢, Type: Refactor ♻️

#54 EP-43 회원가입 페이지 E2E 테스트 코드 작성
  .github/workflows/ci-main.yml
  e2e/signup.spec.ts
  next.config.ts
  playwright.config.ts
  src/app/(auth)/oauth/signup/[...provider]/route.tsx
  src/app/(auth)/signup/page.tsx
  src/app/page.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/SocialButtonGroup.tsx
Labels: Priority: Medium :bookmark:, Type: Test 🧪

#64 EP-49 로그아웃 버튼 구현
  src/app/(auth)/oauth/signup/[...provider]/route.ts
  src/components/auth/LogoutButton.tsx
  src/components/auth/logoutAction.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#61 EP-48 로그인 페이지 구현
  e2e/login.spec.ts
  e2e/signup.spec.ts
  src/apis/auth/index.ts
  src/apis/auth/queries.tsx
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/page.tsx
  src/components/auth/LoginForm.tsx
  src/schemas/index.ts
  src/types/index.ts
  tests/LoginForm.test.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Test 🧪

#63 EP-42 랜딩 페이지 구현
  package-lock.json
  package.json
  src/app/(landings)/layout.tsx
  src/app/(landings)/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/assets/landings/card_1.png
  src/assets/landings/card_2.png
  src/assets/landings/card_3.png
  src/assets/landings/landing_logo.svg
  src/assets/landings/mobile-1.png
  src/assets/landings/mobile-2.png
  src/assets/landings/mobile-3.png
  src/assets/landings/mobile-4.png
  src/assets/landings/tablet-1.png
  src/assets/landings/tablet-2.png
  src/assets/landings/tablet-3.png
  src/assets/landings/tablet-4.png
  src/components/landing/Epigrams.tsx
  src/components/landing/Feature.tsx
  src/components/landing/Footer.tsx
  src/components/landing/Hero.tsx
  src/components/landing/SmoothScroll.tsx
  src/components/ui/header/LandingHeader.tsx
  src/hooks/.gitkeep
  src/hooks/useTypingEffect.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#70 EP-56 textcard 컴포넌트 리팩토링
  src/components/ui/textcard/index.tsx
  src/stories/textCard/index.stories.tsx
  src/types/index.ts
Labels: Priority: Medium :bookmark:, Type: Refactor ♻️

#71 EP-54 랜딩페이지 E2E 테스트 코드 작성
  e2e/example.spec.ts
  e2e/landing.spec.ts
  src/components/landing/Hero.tsx
Labels: Priority: Low 🐢, Type: Test 🧪

#72 EP-57 오늘의 감정 리팩토링
  src/components/ui/emotion/index.tsx
  src/components/ui/emotionButton/index.tsx
  src/constants/emotions.ts
  src/stories/buttons/EmotionButton.stories.tsx
  src/types/index.ts
Labels: Priority: Medium :bookmark:, Type: Refactor ♻️

#78 EP-59 Fix : 로그인, 회원가입 페이지 E2E 오류 수정
  e2e/login.spec.ts
  e2e/signup.spec.ts
Labels: Priority: High 🔥, Type: CrossBrowsing 💻, Type: Test 🧪

#76 EP-50 오늘의 에피그램 컴포넌트 구현
  src/components/epigrams/DailyEpigram.tsx
  src/schemas/index.ts
  src/types/index.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#84 EP-58 스키마 및 타입 구조 수정
  src/actions/logoutAction.ts
  src/apis/auth/index.ts
  src/apis/auth/queries.tsx
  src/apis/auth/schemas.ts
  src/apis/auth/types.ts
  src/apis/comment/index.ts
  src/apis/comment/queries.tsx
  src/apis/comment/schemas.ts
  src/apis/comment/types.ts
  src/apis/emotion-log/index.ts
  src/apis/emotion-log/queries.tsx
  src/apis/emotion-log/schemas.ts
  src/apis/emotion-log/types.ts
  src/apis/epigram/index.ts
  src/apis/epigram/queries.tsx
  src/apis/epigram/schemas.ts
  src/apis/epigram/types.ts
  src/apis/image/index.ts
  src/apis/image/queries.tsx
  src/apis/image/schemas.ts
  src/apis/image/types.ts
  src/apis/user/index.ts
  src/apis/user/schemas.ts
  src/apis/user/types.ts
  src/app/(auth)/oauth/signup/[...provider]/route.ts
  src/assets/images/logo_naver.svg
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/SignupForm.tsx
  src/components/epigrams/DailyEpigram.tsx
  src/components/ui/emotionButton/index.tsx
  src/components/ui/textcard/index.tsx
  src/types/index.ts
  tests/sum.test.ts
Labels: Priority: High 🔥, Type: Refactor ♻️, Type: Setting ⚙

#58 EP-24 댓글 컴포넌트 구현
  package-lock.json
  src/assets/images/mock_profile_img.svg
  src/components/ui/comment/index.tsx
  src/stories/comment/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#86 EP-66 redirect prefetch 동작 오류
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
Labels: Priority: High 🔥, Type: Fix 🐞

#89 EP-65 comment 서비스 로직 구현
  src/apis/comment/index.ts
  src/apis/comment/queries.tsx
  src/apis/comment/schemas.ts
  src/apis/comment/types.ts
Labels: Priority: Medium :bookmark:, Type: API 📬

#88 EP-63 epigram 서비스 로직 구현
  src/apis/epigram/index.ts
  src/apis/epigram/queries.tsx
  src/apis/epigram/schemas.ts
  src/apis/epigram/types.ts
  src/app/api/[...endpoint]/route.ts
  src/components/epigrams/DailyEpigram.tsx
Labels: Priority: Medium :bookmark:, Type: API 📬

#92 EP-61 EP-62 User, Image API 함수 구현
  src/apis/comment/queries.tsx
  src/apis/image/index.ts
  src/apis/image/queries.tsx
  src/apis/image/schemas.ts
  src/apis/image/types.ts
  src/apis/user/index.ts
  src/apis/user/queries.tsx
  src/apis/user/schemas.ts
  src/apis/user/types.ts
Labels: Priority: Medium :bookmark:, Type: API 📬

#95 EP-64 EmotionLog API 구현
  src/apis/emotion-log/index.ts
  src/apis/emotion-log/queries.tsx
  src/apis/emotion-log/schemas.ts
  src/apis/emotion-log/types.ts
Labels: Priority: Medium :bookmark:, Type: API 📬

#96 EP-69 rounded-button 확장성 개선 및 스타일 분리 작업
  src/components/ui/buttons/roundedButton.tsx
  src/stories/buttons/roundedButton.stories.tsx
Labels: Priority: High 🔥, Type: Refactor ♻️

#98 EP-70 ispublic -> isOn으로 수정
  src/components/ui/toggleBtn/index.tsx
  src/stories/toggleBtn/index.stories.tsx
Labels: Priority: Low 🐢, Type: Refactor ♻️

#104 EP-73 에피그램 수정/추가 폼 컴포넌트 구현
  jest.config.ts
  src/app/(after-login)/addepigram/page.tsx
  src/components/addEditForm/AddEditEpigramForm.tsx
  src/components/addEditForm/schemas.ts
  src/components/addEditForm/types.ts
  src/components/ui/header/MainHeader.tsx
  src/components/ui/textarea/index.tsx
  src/components/ui/textcard/index.tsx
  src/stories/textCard/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#105 EP-72 edit-add 페이지 Content 컴포넌트 제작
  src/components/addEditForm/types.ts
  src/components/edit/Content.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#103 EP-55 오늘의 감정 컴포넌트 구현(메인페이지)
  src/apis/emotion-log/index.ts
  src/apis/emotion-log/queries.tsx
  src/apis/emotion-log/schemas.ts
  src/app/api/[...endpoint]/route.ts
  src/components/epigrams/DailyEmotion.tsx
  src/components/ui/emotionButton/index.tsx
  src/constants/emotions.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#106 EP-68 에피그램 리스트 컴포넌트 구현(메인페이지)
  src/app/(after-login)/epigrams/page.tsx
  src/components/epigrams/DailyEpigram.tsx
  src/components/epigrams/EpigramList.tsx
  src/components/ui/header/MainHeader.tsx
  src/components/ui/skeletons/EpigramCardSkeleton.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#108 EP-75 edit-add 페이지 Author 컴포넌트 제작
  src/components/addEditForm/types.ts
  src/components/edit/Author.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#110 EP-76 edit-add 페이지 Tags 컴포넌트 제작
  src/components/addEditForm/types.ts
  src/components/edit/Tags.tsx
  src/components/ui/Field/Input.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#102 EP-67 메인페이지 댓글 리스트 컴포넌트 구현
  src/components/epigrams/CommentList.tsx
  src/components/epigrams/EditCommentModal.tsx
  src/components/ui/comment/index.tsx
  src/components/ui/skeletons/CommentLIstSkeleton.tsx
  src/utils/getTimeElapsed.ts
  tests/getTimeElapsed.test.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Test 🧪

#125 EP-86 Refactor : emotion 컴포넌트 사이즈 추가
  src/components/ui/emotion/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor ♻️

#120 EP-71 Protected Page Header 기능 완성
  src/app/(after-login)/(background-gray)/epigrams/[id]/page.tsx
  src/app/(after-login)/(background-gray)/epigrams/page.tsx
  src/app/(after-login)/(background-gray)/feed/page.tsx
  src/app/(after-login)/(background-gray)/layout.tsx
  src/app/(after-login)/(background-gray)/mypage/page.tsx
  src/app/(after-login)/(background-white)/addepigram/page.tsx
  src/app/(after-login)/(background-white)/epigrams/[id]/edit/page.tsx
  src/app/(after-login)/(background-white)/layout.tsx
  src/app/(after-login)/(background-white)/search/page.tsx
  src/app/(after-login)/edittest/page.tsx
  src/app/(after-login)/epigrams/[id]/edit/page.tsx
  src/app/(after-login)/epigrams/[id]/page.tsx
  src/app/(after-login)/epigrams/page.tsx
  src/app/(after-login)/layout.tsx
  src/components/addEditForm/AddEpigramForm.tsx
  src/components/addEditForm/Author.tsx
  src/components/addEditForm/EditEpigramForm.tsx
  src/components/addEditForm/EpigramFormLayout.tsx
  src/components/addEditForm/Tags.tsx
  src/components/ui/header/MainHeader.tsx
  src/components/ui/sideBar/index.tsx
  src/stories/sideBar/index.stories.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Refactor ♻️

#124 EP-83 에픽그램 생성 페이지 api 연결 & 해당 id로 페이지로 이동
  src/components/addEditForm/AddEpigramForm.tsx
  tests/addEpigramForm.test.tsx
Labels: Priority: High 🔥, Type: API 📬, Type: Feature ✨

#127 EP-85 감정 달력 컴포넌트
  src/apis/emotion-log/index.ts
  src/apis/emotion-log/queries.tsx
  src/apis/emotion-log/schemas.ts
  src/components/epigrams/DailyEmotion.tsx
  src/components/mypage/DailyEmotion.tsx
  src/components/mypage/EmotionCalendar.tsx
  src/components/ui/emotionButton/index.tsx
  src/constants/calendar.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Refactor ♻️

#129 EP-82 에픽그램 수정 페이지 api 연결 & 해당 id로 페이지로 이동
  src/app/(after-login)/(background-white)/epigrams/[id]/edit/page.tsx
  src/components/addEditForm/EditEpigramForm.tsx
Labels: Priority: Medium :bookmark:, Type: API 📬, Type: Feature ✨

#130 EP-89 스토리북 mdx 파일
  .github/workflows/storybook.yml
  src/app/globals.css
  src/stories/DropdownMenu/index.stories.tsx
  src/stories/colorsSystem.mdx
  src/stories/typesetSystem.mdx
  src/stories/utilityStyleSystem.mdx
Labels: Priority: Low 🐢, Type: Docs 📃

#131 EP-87 메인 페이지 완성 및 E2E 테스트 코드 작성
  .github/workflows/ci-dev.yml
  e2e/epigrams.spec.ts
  e2e/login.spec.ts
  src/app/(after-login)/(background-gray)/epigrams/page.tsx
  src/app/(after-login)/(background-gray)/layout.tsx
  src/assets/icons/plus_white.svg
  src/components/ui/buttons/AddEpigramButton.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Test 🧪

#136 EP-92 오늘의 에피그램 에러 핸들링
  src/components/epigrams/DailyEpigram.tsx
Labels: Priority: High 🔥, Type: Fix 🐞

#141 EP-96 E2E, 스토리북 메인 병합시 발생하는 에러 해결
  e2e/epigrams.spec.ts
  src/stories/header/MainHeader.stories.tsx
Labels: Priority: High 🔥, Type: Fix 🐞

#133 EP-88 Feat : 감정 차트 구현
  src/apis/emotion-log/schemas.ts
  src/components/epigrams/EmotionChart.tsx
  src/components/epigrams/EmotionChartData.tsx
  src/components/ui/emotion/index.tsx
Labels: Priority: Medium :bookmark:, Type: Html&css 🎨, Type: Refactor ♻️

#145 EP-94 메인페이지 댓글리스트 리팩토링
  src/components/epigrams/CommentEmptyState.tsx
  src/components/epigrams/CommentList.tsx
  src/components/epigrams/EditCommentModal.tsx
  src/components/ui/comment/index.tsx
  src/hooks/useCommentActions.tsx
Labels: Priority: Low 🐢, Type: Refactor ♻️

#148 EP-95 마이페이지 캘린더와 감정 차트 전역 상태 관리 구현
  src/app/(after-login)/(background-gray)/mypage/layout.tsx
  src/components/mypage/EmotionCalendar.tsx
  src/components/mypage/EmotionChart.tsx
  src/components/mypage/EmotionChartData.tsx
  src/context/MypageProvider.tsx
  src/context/schemas.ts
  src/context/types.ts
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#144 EP-81 에피그램 상세 페이지 내용부분 구현
  src/apis/epigram/index.ts
  src/apis/epigram/queries.tsx
  src/app/(after-login)/(background-gray)/epigrams/[id]/error.tsx
  src/app/(after-login)/(background-gray)/epigrams/[id]/page.tsx
  src/assets/icons/like_outlined.svg
  src/components/epigramDetail/epigramContent.tsx
  src/components/ui/textcard/index.tsx
  src/stores/ModalStore.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#149 EP-93 로그인 페이지 개선
  public/logo.png
  src/app/(auth)/login/layout.tsx
  src/app/(auth)/login/page.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SocialButtonGroup.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#152 EP-97 에픽그램 수정, 생성 페이지 리팩토링
  src/components/addEditForm/AddEpigramForm.tsx
  src/components/addEditForm/Author.tsx
  src/components/addEditForm/EditEpigramForm.tsx
  src/components/addEditForm/schemas.ts
Labels: Priority: High 🔥, Type: Improve UX :arrow_up:, Type: Refactor ♻️

#147 EP-90 에픽그램 생성 페이지 E2E 테스트
  e2e/addEpigrams.spec.ts
  package-lock.json
  src/utils/navigate/navigateToAddEpigramPage.ts
Labels: Priority: Low 🐢, Type: Test 🧪

#156 에피그램 상세페이지 오류 수정 및 리팩토링
  src/components/epigramDetail/epigramContent.tsx
Labels: Priority: Medium :bookmark:, Type: Fix 🐞, Type: Refactor ♻️

#155 EP-98 랜딩페이지 metadata 추가 작업
  public/meta.png
  public/shortcut_apple.png
  src/app/(landings)/layout.tsx
Labels: Priority: Low 🐢, Type: Accessibility 🥰

#143 EP-79 검색입력 폼 구현 완료
  package-lock.json
  src/app/(after-login)/(background-white)/search/page.tsx
  src/assets/icons/search_icon.svg
  src/components/ui/searchForm/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨
