Repository rak517/Epigram, pull requests merged in 2025-04, with the labels that each got.

#163 EP-106 회원가입 페이지 개선
  src/app/(auth)/signup/page.tsx
  src/app/robots.ts
  src/components/auth/SignupForm.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#157 EP-100 에픽그램 수정 페이지 E2E 테스트
  e2e/addEpigrams.spec.ts
  e2e/editEpigrams.spec.ts
  src/utils/navigate/navigateToAddEpigramPage.ts
Labels: Priority: Medium :bookmark:, Type: Test 🧪

#158 EP-99 Feat : 마이페이지 일부 구현
  src/app/(after-login)/(background-gray)/mypage/page.tsx
  src/app/globals.css
  src/components/mypage/DailyEmotion.tsx
  src/components/ui/avatars/index.tsx
  src/context/MypageProvider.tsx
  src/context/schemas.ts
Labels: Priority: Medium :bookmark:, Type: Html&css 🎨

#170 EP-108 피드 페이지 구현 및 E2E
  .github/workflows/ci-main.yml
  e2e/feed.spec.ts
  src/app/(after-login)/(background-gray)/feed/page.tsx
  src/app/(auth)/oauth/signup/[...provider]/route.ts
  src/app/api/[...endpoint]/route.ts
  src/app/api/auth/refresh-token/route.ts
  src/components/feed/EpigramList.tsx
  src/components/ui/skeletons/FeedCardSkeleton.tsx
  src/utils/network/axiosServerHelper.ts
Labels: Priority: High 🔥, Type: Fix 🐞, Type: Feature ✨

#160 EP-103 Feat : 마이페이지 내 에피그램, 내 댓글에 대한 기능 구현
  src/components/mypage/MyEpigramComments.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#167 EP-104 에피그램 상세페이지 댓글 컴포넌트 구현
  src/app/(after-login)/(background-gray)/epigrams/[id]/page.tsx
  src/assets/icons/lock.svg
  src/assets/icons/lock_black.svg
  src/components/epigramDetail/EpigramComment.tsx
  src/components/epigramDetail/EpigramCommentLayout.tsx
  src/components/epigramDetail/EpigramContent.tsx
  src/components/epigramDetail/ProfileModal.tsx
  src/components/ui/comment/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨, Type: Html&css 🎨

#174 EP-109 Tag 컴포넌트 파일명과 통일
  src/components/addEditForm/Tags.tsx
Labels: Priority: Low 🐢, Type: Refactor ♻️

#180 EP-112 에피그램 상세페이지 개선작업
  src/apis/epigram/queries.tsx
  src/apis/epigram/types.ts
  src/app/layout.tsx
  src/components/epigramDetail/EpigramContent.tsx
  src/utils/copyCurrentUrl.ts
  src/utils/toast/Toast.tsx
  src/utils/toast/ToastContext.tsx
Labels: Priority: Low 🐢, Type: Fix 🐞, Type: Refactor ♻️

#179 EP-107 랜딩페이지 개선 작업
  e2e/landing.spec.ts
  src/assets/landings/desktop-1.png
  src/assets/landings/desktop-2.png
  src/assets/landings/desktop-3.png
  src/assets/landings/desktop-4.png
  src/assets/landings/img_Desktop_landing01.svg
  src/assets/landings/img_Desktop_landing02.svg
  src/assets/landings/img_Desktop_landing03.svg
  src/components/landing/Epigrams.tsx
  src/components/landing/Feature.tsx
  src/components/landing/Hero.tsx
  src/components/ui/header/LandingHeader.tsx
Labels: Priority: Low 🐢, Type: Refactor ♻️

#176 EP-114 404페이지 및 전역 error 페이지
  src/app/(after-login)/(background-gray)/feed/page.tsx
  src/app/error.tsx
  src/app/globals.css
  src/app/not-found.tsx
  src/stories/typesetSystem.mdx
  src/stories/utilityStyleSystem.mdx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#184 EP-119 메인페이지 metadata 추가
  src/app/(after-login)/(background-gray)/epigrams/page.tsx
Labels: Priority: Low 🐢, Type: Accessibility 🥰

#190 EP-116 검색페이지-최근검색어 저장 기능 구현
  src/app/(after-login)/(background-white)/search/page.tsx
  src/components/ui/searchForm/index.tsx
  src/components/ui/searchSave/index.tsx
Labels: Priority: Medium :bookmark:, Type: Feature ✨

#188 EP-117 에피그램 상세페이지 e2e
  e2e/epigramDetail.spec.ts
  src/app/(after-login)/(background-gray)/epigrams/[id]/page.tsx
  src/components/epigramDetail/EpigramComment.tsx
  src/components/epigramDetail/EpigramContent.tsx
  src/components/epigramDetail/ProfileModal.tsx
  src/utils/copyCurrentUrl.ts
  src/utils/toast/Toast.tsx
Labels: Priority: Medium :bookmark:, Type: Html&css 🎨

#191 EP-115 route handler 리팩토링 및 기타 버그 수정
  src/apis/epigram/queries.tsx
  src/app/api/[...endpoint]/route.ts
  src/components/epigramDetail/EpigramComment.tsx
  src/components/epigramDetail/ProfileModal.tsx
  src/components/ui/header/LandingHeader.tsx
  src/components/ui/modals/index.tsx
  src/components/ui/sideBar/index.tsx
  src/utils/toast/Toast.tsx
Labels: Priority: High 🔥, Type: Fix 🐞, Type: Refactor ♻️

#187 EP-120 헤더 프로필 영역 클릭 시 드롭다운 적용
  clicked-icon.png
  e2e/epigrams.spec.ts
  e2e/feed.spec.ts
  e2e/landing.spec.ts
  src/components/ui/DropdownMenu/index.tsx
  src/components/ui/header/LandingHeader.tsx
  src/components/ui/header/MainHeader.tsx
  src/hooks/useHandleHeaderSelect.ts
Labels: Priority: Medium :bookmark:, Type: Refactor ♻️, Type: Test 🧪

#189 EP-110 마이페이지 구현과 E2E 테스트 구현
  e2e/mypage.spec.ts
  src/apis/image/queries.tsx
  src/app/(after-login)/(background-gray)/mypage/page.tsx
  src/components/mypage/EmotionChart.tsx
  src/components/mypage/MyEpigramComments.tsx
  src/components/ui/emotion/index.tsx
  src/components/ui/emotionButton/index.tsx
Labels: Priority: Medium :bookmark:, Type: Test 🧪

#194 EP-122 GA/GTM 추가
  .github/workflows/ci-dev.yml
  .github/workflows/ci-main.yml
  declaration.d.ts
  package-lock.json
  package.json
  src/app/(landings)/page.tsx
  src/app/layout.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/LogoutButton.tsx
  src/components/auth/SignupForm.tsx
  src/components/auth/SocialButtonGroup.tsx
  src/components/landing/Hero.tsx
  src/hooks/useHandleHeaderSelect.ts
  src/hooks/useScrollTracking.ts
  src/utils/GAtrackPageView.tsx
  src/utils/analytics.ts
Labels: Priority: Low 🐢, Type: Feature ✨

#200 EP-126 Refactor : 감정 차트 리팩토링 작업
  src/apis/emotion-log/schemas.ts
  src/components/mypage/EmotionChart.tsx
  src/components/mypage/EmotionChartData.tsx
  src/components/ui/emotion/EmotionPath.tsx
  src/components/ui/emotion/index.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor ♻️

#203 EP-128 마이페이지 리팩토링
  src/app/(after-login)/(background-gray)/(addEpigram-button)/epigrams/[id]/error.tsx
  src/app/(after-login)/(background-gray)/(addEpigram-button)/epigrams/[id]/page.tsx
  src/app/(after-login)/(background-gray)/(addEpigram-button)/epigrams/page.tsx
  src/app/(after-login)/(background-gray)/(addEpigram-button)/feed/page.tsx
  src/app/(after-login)/(background-gray)/(addEpigram-button)/layout.tsx
  src/app/(after-login)/(background-gray)/mypage/page.tsx
  src/components/mypage/MyEpigramComments.tsx
Labels: Priority: Medium :bookmark:, Type: Html&css 🎨, Type: Refactor ♻️

#202 EP-124 에피그램 상세페이지 lighthouse 개선
  e2e/epigramDetail.spec.ts
  package-lock.json
  src/app/(after-login)/(background-gray)/(addEpigram-button)/epigrams/[id]/page.tsx
  src/components/epigramDetail/EpigramComment.tsx
  src/components/epigramDetail/EpigramContent.tsx
  src/components/epigramDetail/EpigramDropdown.tsx
  src/components/epigramDetail/TagsClient.tsx
  src/components/ui/buttons/AddEpigramButton.tsx
  src/components/ui/textcard/textcardServer.tsx
  src/components/ui/toggleBtn/index.tsx
Labels: Priority: Low 🐢, Type: Refactor ♻️

#209 EP-131 fixed : 마이페이지 E2E 테스트 오류에 대한 수정
  e2e/mypage.spec.ts
  src/components/mypage/EmotionCalendar.tsx
Labels: Priority: High 🔥, Type: Fix 🐞

#205 EP-127 헤더 스토리북 useRouter 에러 해결
  .storybook/main.ts
  package-lock.json
  src/components/ui/header/LandingHeader.tsx
  src/stories/header/LandingHeader.stories.tsx
  src/stories/header/MainHeader.stories.tsx
Labels: Priority: High 🔥, Type: Fix 🐞

#212 EP-132 에피그램 상세페이지 서버컴포넌트 페칭 이전으로 롤백
  src/app/(after-login)/(background-gray)/(addEpigram-button)/epigrams/[id]/page.tsx
  src/components/epigramDetail/EpigramContent.tsx
  src/components/epigramDetail/EpigramDropdown.tsx
  src/components/epigramDetail/TagsClient.tsx
Labels: Priority: High 🔥, Type: Fix 🐞

#218 EP-129 마이페이지 light house 최적화 작업
  src/app/(after-login)/(background-gray)/mypage/page.tsx
  src/components/mypage/EmotionChartSection.tsx
  src/components/mypage/UserProfileLayout.tsx
  src/context/MypageProvider.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor ♻️
